const PREFERENCE_ENUM = [
    "Woolen Craft",
    "Poetry",
    "Exclusive",
    "Paintings",
    "Sculptures",
    "Wooden Crafts",
    "Textile Art",
    "Ceramics",
    "Jewelry Design",
    "Glass Art",
    "Metalwork",
    "Paper Crafts",
    "Mixed Media",
    "Photography",
    "Digital Art",
    "Calligraphy",
    "Printmaking",
    "Mosaic Art",
    "Leatherwork",
    "Pottery",
    "Fiber Art",
    "Illustration",
    "Installation Art",
];

const SERVICES_ENUM = [
    "Room Decor",
    "1:1 Art Session",
    "Consultation",
    "Art Therapy",
    "Custom Art Commission",
    "Drawing Lessons",
    "Painting Workshop",
    "Sculpture Class",
    "Textile Art Tutorial",
    "Jewelry Making Session",
    "Ceramic Workshop",
    "Photography Guidance",
    "Digital Art Training",
    "Calligraphy Course",
    "Printmaking Session",
    "Mosaic Art Class",
    "Leatherwork Workshop",
    "Pottery Tutorial",
    "Fiber Art Instruction",
    "Art Installation Service",
];

export { PREFERENCE_ENUM, SERVICES_ENUM };
